const teams = [
  {
    name: "Anaheim Ducks",
    city: "Anaheim",
    league: "NHL",
    year: "1993",
    sport: "hockey",
  },
  {
    name: "Arizona Cardinals",
    city: "Glendale",
    league: "NFL",
    year: "1988",
    sport: "football",
  },
  {
    name: "Arizona Coyotes",
    city: "Glendale",
    league: "NHL",
    year: "1996",
    sport: "hockey",
  },
  {
    name: "Arizona Diamondbacks",
    city: "Phoenix",
    league: "MLB",
    year: "1998",
    sport: "baseball",
  },
  {
    name: "Atlanta Braves",
    city: "Atlanta",
    league: "MLB",
    year: "1966",
    sport: "baseball",
  },
  {
    name: "Atlanta Falcons",
    city: "Atlanta",
    league: "NFL",
    year: "1966",
    sport: "football",
  },
  {
    name: "Atlanta Hawks",
    city: "Atlanta",
    league: "NBA",
    year: "1968",
    sport: "basketball",
  },
  {
    name: "Atlanta United FC",
    city: "Atlanta",
    league: "MLS",
    year: "2017",
    sport: "soccer",
  },
  {
    name: "BC Lions",
    city: "Vancouver",
    league: "CFL",
    year: "1954",
    sport: "football",
  },
  {
    name: "Baltimore Orioles",
    city: "Baltimore",
    league: "MLB",
    year: "1954",
    sport: "baseball",
  },
  {
    name: "Baltimore Ravens",
    city: "Baltimore",
    league: "NFL",
    year: "1996",
    sport: "football",
  },
  {
    name: "Boston Bruins",
    city: "Boston",
    league: "NHL",
    year: "1924",
    sport: "hockey",
  },
  {
    name: "Boston Celtics",
    city: "Boston",
    league: "NBA",
    year: "1946",
    sport: "basketball",
  },
  {
    name: "Boston Red Sox",
    city: "Boston",
    league: "MLB",
    year: "1901",
    sport: "baseball",
  },
  {
    name: "Brooklyn Nets",
    city: "New York City",
    league: "NBA",
    year: "1967",
    sport: "basketball",
  },
  {
    name: "Buffalo Bills",
    city: "Orchard Park",
    league: "NFL",
    year: "1960",
    sport: "football",
  },
  {
    name: "Buffalo Sabres",
    city: "Buffalo",
    league: "NHL",
    year: "1970",
    sport: "hockey",
  },
  {
    name: "Calgary Flames",
    city: "Calgary",
    league: "NHL",
    year: "1980",
    sport: "hockey",
  },
  {
    name: "Calgary Stampeders",
    city: "Calgary",
    league: "CFL",
    year: "1945",
    sport: "football",
  },
  {
    name: "Carolina Hurricanes",
    city: "Raleigh",
    league: "NHL",
    year: "1997",
    sport: "hockey",
  },
  {
    name: "Carolina Panthers",
    city: "Charlotte",
    league: "NFL",
    year: "1995",
    sport: "football",
  },
  {
    name: "Charlotte Hornets",
    city: "Charlotte",
    league: "NBA",
    year: "2004",
    sport: "basketball",
  },
  {
    name: "Chicago Bears",
    city: "Chicago",
    league: "NFL",
    year: "1921",
    sport: "football",
  },
  {
    name: "Chicago Blackhawks",
    city: "Chicago",
    league: "NHL",
    year: "1926",
    sport: "hockey",
  },
  {
    name: "Chicago Bulls",
    city: "Chicago",
    league: "NBA",
    year: "1966",
    sport: "basketball",
  },
  {
    name: "Chicago Cubs",
    city: "Chicago",
    league: "MLB",
    year: "1870",
    sport: "baseball",
  },
  {
    name: "Chicago Fire",
    city: "Bridgeview",
    league: "MLS",
    year: "1997",
    sport: "soccer",
  },
  {
    name: "Chicago White Sox",
    city: "Chicago",
    league: "MLB",
    year: "1901",
    sport: "baseball",
  },
  {
    name: "Cincinnati Bengals",
    city: "Cincinnati",
    league: "NFL",
    year: "1968",
    sport: "football",
  },
  {
    name: "Cincinnati Reds",
    city: "Cincinnati",
    league: "MLB",
    year: "1882",
    sport: "baseball",
  },
  {
    name: "Cleveland Browns",
    city: "Cleveland",
    league: "NFL",
    year: "1946",
    sport: "football",
  },
  {
    name: "Cleveland Cavaliers",
    city: "Cleveland",
    league: "NBA",
    year: "1970",
    sport: "basketball",
  },
  {
    name: "Cleveland Indians",
    city: "Cleveland",
    league: "MLB",
    year: "1901",
    sport: "baseball",
  },
  {
    name: "Colorado Avalanche",
    city: "Denver",
    league: "NHL",
    year: "1995",
    sport: "hockey",
  },
  {
    name: "Colorado Rapids",
    city: "Commerce City",
    league: "MLS",
    year: "1996",
    sport: "soccer",
  },
  {
    name: "Colorado Rockies",
    city: "Denver",
    league: "MLB",
    year: "1993",
    sport: "baseball",
  },
  {
    name: "Columbus Blue Jackets",
    city: "Columbus",
    league: "NHL",
    year: "2000",
    sport: "hockey",
  },
  {
    name: "Columbus Crew SC",
    city: "Columbus",
    league: "MLS",
    year: "1996",
    sport: "soccer",
  },
  {
    name: "D.C. United",
    city: "Washington",
    league: "MLS",
    year: "1996",
    sport: "soccer",
  },
  {
    name: "Dallas Cowboys",
    city: "Arlington",
    league: "NFL",
    year: "1960",
    sport: "football",
  },
  {
    name: "Dallas Mavericks",
    city: "Dallas",
    league: "NBA",
    year: "1980",
    sport: "basketball",
  },
  {
    name: "Dallas Stars",
    city: "Dallas",
    league: "NHL",
    year: "1993",
    sport: "hockey",
  },
  {
    name: "Denver Broncos",
    city: "Denver",
    league: "NFL",
    year: "1960",
    sport: "football",
  },
  {
    name: "Denver Nuggets",
    city: "Denver",
    league: "NBA",
    year: "1967",
    sport: "basketball",
  },
  {
    name: "Detroit Lions",
    city: "Detroit",
    league: "NFL",
    year: "1934",
    sport: "football",
  },
  {
    name: "Detroit Pistons",
    city: "Detroit",
    league: "NBA",
    year: "1957",
    sport: "basketball",
  },
  {
    name: "Detroit Red Wings",
    city: "Detroit",
    league: "NHL",
    year: "1926",
    sport: "hockey",
  },
  {
    name: "Detroit Tigers",
    city: "Detroit",
    league: "MLB",
    year: "1901",
    sport: "baseball",
  },
  {
    name: "Edmonton Eskimos",
    city: "Edmonton",
    league: "CFL",
    year: "1949",
    sport: "football",
  },
  {
    name: "Edmonton Oilers",
    city: "Edmonton",
    league: "NHL",
    year: "1972",
    sport: "hockey",
  },
  {
    name: "FC Dallas",
    city: "Frisco",
    league: "MLS",
    year: "1996",
    sport: "soccer",
  },
  {
    name: "Florida Panthers",
    city: "Sunrise",
    league: "NHL",
    year: "1993",
    sport: "hockey",
  },
  {
    name: "Golden State Warriors",
    city: "Oakland",
    league: "NBA",
    year: "1962",
    sport: "basketball",
  },
  {
    name: "Green Bay Packers",
    city: "Green Bay",
    league: "NFL",
    year: "1921",
    sport: "football",
  },
  {
    name: "Hamilton Tiger-Cats",
    city: "Hamilton",
    league: "CFL",
    year: "1950",
    sport: "football",
  },
  {
    name: "Houston Astros",
    city: "Houston",
    league: "MLB",
    year: "1962",
    sport: "baseball",
  },
  {
    name: "Houston Dynamo",
    city: "Houston",
    league: "MLS",
    year: "2006",
    sport: "soccer",
  },
  {
    name: "Houston Rockets",
    city: "Houston",
    league: "NBA",
    year: "1971",
    sport: "basketball",
  },
  {
    name: "Houston Texans",
    city: "Houston",
    league: "NFL",
    year: "2002",
    sport: "football",
  },
  {
    name: "Indiana Pacers",
    city: "Indianapolis",
    league: "NBA",
    year: "1967",
    sport: "basketball",
  },
  {
    name: "Indianapolis Colts",
    city: "Indianapolis",
    league: "NFL",
    year: "1984",
    sport: "football",
  },
  {
    name: "Jacksonville Jaguars",
    city: "Jacksonville",
    league: "NFL",
    year: "1995",
    sport: "football",
  },
  {
    name: "Kansas City Chiefs",
    city: "Kansas City",
    league: "NFL",
    year: "1963",
    sport: "football",
  },
  {
    name: "Kansas City Royals",
    city: "Kansas City",
    league: "MLB",
    year: "1969",
    sport: "baseball",
  },
  {
    name: "LA Galaxy",
    city: "Carson",
    league: "MLS",
    year: "1996",
    sport: "soccer",
  },
  {
    name: "Los Angeles Angels",
    city: "Anaheim",
    league: "MLB",
    year: "1961",
    sport: "baseball",
  },
  {
    name: "Los Angeles Chargers",
    city: "Carson",
    league: "NFL",
    year: "2017",
    sport: "football",
  },
  {
    name: "Los Angeles Clippers",
    city: "Los Angeles",
    league: "NBA",
    year: "1984",
    sport: "basketball",
  },
  {
    name: "Los Angeles Dodgers",
    city: "Los Angeles",
    league: "MLB",
    year: "1958",
    sport: "baseball",
  },
  {
    name: "Los Angeles FC",
    city: "Los Angeles",
    league: "MLS",
    year: "2018",
    sport: "soccer",
  },
  {
    name: "Los Angeles Kings",
    city: "Los Angeles",
    league: "NHL",
    year: "1967",
    sport: "hockey",
  },
  {
    name: "Los Angeles Lakers",
    city: "Los Angeles",
    league: "NBA",
    year: "1960",
    sport: "basketball",
  },
  {
    name: "Los Angeles Rams",
    city: "Los Angeles",
    league: "NFL",
    year: "2016",
    sport: "football",
  },
  {
    name: "Memphis Grizzlies",
    city: "Memphis",
    league: "NBA",
    year: "2001",
    sport: "basketball",
  },
  {
    name: "Miami Dolphins",
    city: "Miami Gardens",
    league: "NFL",
    year: "1966",
    sport: "football",
  },
  {
    name: "Miami Heat",
    city: "Miami",
    league: "NBA",
    year: "1988",
    sport: "basketball",
  },
  {
    name: "Miami Marlins",
    city: "Miami",
    league: "MLB",
    year: "1993",
    sport: "baseball",
  },
  {
    name: "Milwaukee Brewers",
    city: "Milwaukee",
    league: "MLB",
    year: "1970",
    sport: "baseball",
  },
  {
    name: "Milwaukee Bucks",
    city: "Milwaukee",
    league: "NBA",
    year: "1968",
    sport: "basketball",
  },
  {
    name: "Minnesota Timberwolves",
    city: "Minneapolis",
    league: "NBA",
    year: "1989",
    sport: "basketball",
  },
  {
    name: "Minnesota Twins",
    city: "Minneapolis",
    league: "MLB",
    year: "1961",
    sport: "baseball",
  },
  {
    name: "Minnesota United FC",
    city: "St. Paul",
    league: "MLS",
    year: "2017",
    sport: "soccer",
  },
  {
    name: "Minnesota Vikings",
    city: "Minneapolis",
    league: "NFL",
    year: "1961",
    sport: "football",
  },
  {
    name: "Minnesota Wild",
    city: "St. Paul",
    league: "NHL",
    year: "2000",
    sport: "hockey",
  },
  {
    name: "Montreal Alouettes",
    city: "Montreal",
    league: "CFL",
    year: "1946/1996",
    sport: "football",
  },
  {
    name: "Montreal Canadiens",
    city: "Montreal",
    league: "NHL",
    year: "1909",
    sport: "hockey",
  },
  {
    name: "Montreal Impact",
    city: "Montreal",
    league: "MLS",
    year: "2012",
    sport: "soccer",
  },
  {
    name: "Nashville Predators",
    city: "Nashville",
    league: "NHL",
    year: "1998",
    sport: "hockey",
  },
  {
    name: "New England Patriots",
    city: "Foxborough",
    league: "NFL",
    year: "1960",
    sport: "football",
  },
  {
    name: "New England Revolution",
    city: "Foxborough",
    league: "MLS",
    year: "1996",
    sport: "soccer",
  },
  {
    name: "New Jersey Devils",
    city: "Newark",
    league: "NHL",
    year: "1982",
    sport: "hockey",
  },
  {
    name: "New Orleans Pelicans",
    city: "New Orleans",
    league: "NBA",
    year: "2002",
    sport: "basketball",
  },
  {
    name: "New Orleans Saints",
    city: "New Orleans",
    league: "NFL",
    year: "1967",
    sport: "football",
  },
  {
    name: "New York City FC",
    city: "New York City",
    league: "MLS",
    year: "2015",
    sport: "soccer",
  },
  {
    name: "New York Giants",
    city: "East Rutherford",
    league: "NFL",
    year: "1925",
    sport: "football",
  },
  {
    name: "New York Islanders",
    city: "New York City",
    league: "NHL",
    year: "1972",
    sport: "hockey",
  },
  {
    name: "New York Jets",
    city: "East Rutherford",
    league: "NFL",
    year: "1960",
    sport: "football",
  },
  {
    name: "New York Knicks",
    city: "New York City",
    league: "NBA",
    year: "1946",
    sport: "basketball",
  },
  {
    name: "New York Mets",
    city: "New York City",
    league: "MLB",
    year: "1962",
    sport: "baseball",
  },
  {
    name: "New York Rangers",
    city: "New York City",
    league: "NHL",
    year: "1926",
    sport: "hockey",
  },
  {
    name: "New York Red Bulls",
    city: "Harrison",
    league: "MLS",
    year: "1996",
    sport: "soccer",
  },
  {
    name: "New York Yankees",
    city: "New York City",
    league: "MLB",
    year: "1903",
    sport: "baseball",
  },
  {
    name: "Oakland Athletics",
    city: "Oakland",
    league: "MLB",
    year: "1968",
    sport: "baseball",
  },
  {
    name: "Oakland Raiders",
    city: "Oakland",
    league: "NFL",
    year: "1995",
    sport: "football",
  },
  {
    name: "Oklahoma City Thunder",
    city: "Oklahoma City",
    league: "NBA",
    year: "2008",
    sport: "basketball",
  },
  {
    name: "Orlando City SC",
    city: "Orlando",
    league: "MLS",
    year: "2015",
    sport: "soccer",
  },
  {
    name: "Orlando Magic",
    city: "Orlando",
    league: "NBA",
    year: "1989",
    sport: "basketball",
  },
  {
    name: "Ottawa Redblacks",
    city: "Ottawa",
    league: "CFL",
    year: "2014",
    sport: "football",
  },
  {
    name: "Ottawa Senators",
    city: "Ottawa",
    league: "NHL",
    year: "1992",
    sport: "hockey",
  },
  {
    name: "Philadelphia 76ers",
    city: "Philadelphia",
    league: "NBA",
    year: "1963",
    sport: "basketball",
  },
  {
    name: "Philadelphia Eagles",
    city: "Philadelphia",
    league: "NFL",
    year: "1933",
    sport: "football",
  },
  {
    name: "Philadelphia Flyers",
    city: "Philadelphia",
    league: "NHL",
    year: "1967",
    sport: "hockey",
  },
  {
    name: "Philadelphia Phillies",
    city: "Philadelphia",
    league: "MLB",
    year: "1883",
    sport: "baseball",
  },
  {
    name: "Philadelphia Union",
    city: "Chester",
    league: "MLS",
    year: "2010",
    sport: "soccer",
  },
  {
    name: "Phoenix Suns",
    city: "Phoenix",
    league: "NBA",
    year: "1968",
    sport: "basketball",
  },
  {
    name: "Pittsburgh Penguins",
    city: "Pittsburgh",
    league: "NHL",
    year: "1967",
    sport: "hockey",
  },
  {
    name: "Pittsburgh Pirates",
    city: "Pittsburgh",
    league: "MLB",
    year: "1882",
    sport: "baseball",
  },
  {
    name: "Pittsburgh Steelers",
    city: "Pittsburgh",
    league: "NFL",
    year: "1933",
    sport: "football",
  },
  {
    name: "Portland Timbers",
    city: "Portland",
    league: "MLS",
    year: "2011",
    sport: "soccer",
  },
  {
    name: "Portland Trail Blazers",
    city: "Portland",
    league: "NBA",
    year: "1970",
    sport: "basketball",
  },
  {
    name: "Real Salt Lake",
    city: "Sandy",
    league: "MLS",
    year: "2005",
    sport: "soccer",
  },
  {
    name: "Sacramento Kings",
    city: "Sacramento",
    league: "NBA",
    year: "1985",
    sport: "basketball",
  },
  {
    name: "San Antonio Spurs",
    city: "San Antonio",
    league: "NBA",
    year: "1973",
    sport: "basketball",
  },
  {
    name: "San Diego Padres",
    city: "San Diego",
    league: "MLB",
    year: "1969",
    sport: "baseball",
  },
  {
    name: "San Francisco 49ers",
    city: "Santa Clara",
    league: "NFL",
    year: "1946",
    sport: "football",
  },
  {
    name: "San Francisco Giants",
    city: "San Francisco",
    league: "MLB",
    year: "1958",
    sport: "baseball",
  },
  {
    name: "San Jose Earthquakes",
    city: "San Jose",
    league: "MLS",
    year: "1996",
    sport: "soccer",
  },
  {
    name: "San Jose Sharks",
    city: "San Jose",
    league: "NHL",
    year: "1991",
    sport: "hockey",
  },
  {
    name: "Saskatchewan Roughriders",
    city: "Regina",
    league: "CFL",
    year: "1910",
    sport: "football",
  },
  {
    name: "Seattle Mariners",
    city: "Seattle",
    league: "MLB",
    year: "1977",
    sport: "baseball",
  },
  {
    name: "Seattle Seahawks",
    city: "Seattle",
    league: "NFL",
    year: "1976",
    sport: "football",
  },
  {
    name: "Seattle Sounders FC",
    city: "Seattle",
    league: "MLS",
    year: "2009",
    sport: "soccer",
  },
  {
    name: "Sporting Kansas City",
    city: "Kansas City",
    league: "MLS",
    year: "1996",
    sport: "soccer",
  },
  {
    name: "St. Louis Blues",
    city: "St. Louis",
    league: "NHL",
    year: "1967",
    sport: "hockey",
  },
  {
    name: "St. Louis Cardinals",
    city: "St. Louis",
    league: "MLB",
    year: "1882",
    sport: "baseball",
  },
  {
    name: "Tampa Bay Buccaneers",
    city: "Tampa",
    league: "NFL",
    year: "1976",
    sport: "football",
  },
  {
    name: "Tampa Bay Lightning",
    city: "Tampa",
    league: "NHL",
    year: "1992",
    sport: "hockey",
  },
  {
    name: "Tampa Bay Rays",
    city: "St. Petersburg",
    league: "MLB",
    year: "1998",
    sport: "baseball",
  },
  {
    name: "Tennessee Titans",
    city: "Nashville",
    league: "NFL",
    year: "1997",
    sport: "football",
  },
  {
    name: "Texas Rangers",
    city: "Arlington",
    league: "MLB",
    year: "1972",
    sport: "baseball",
  },
  {
    name: "Toronto Argonauts",
    city: "Toronto",
    league: "CFL",
    year: "1873",
    sport: "football",
  },
  {
    name: "Toronto Blue Jays",
    city: "Toronto",
    league: "MLB",
    year: "1977",
    sport: "baseball",
  },
  {
    name: "Toronto FC",
    city: "Toronto",
    league: "MLS",
    year: "2007",
    sport: "soccer",
  },
  {
    name: "Toronto Maple Leafs",
    city: "Toronto",
    league: "NHL",
    year: "1917",
    sport: "hockey",
  },
  {
    name: "Toronto Raptors",
    city: "Toronto",
    league: "NBA",
    year: "1995",
    sport: "basketball",
  },
  {
    name: "Utah Jazz",
    city: "Salt Lake City",
    league: "NBA",
    year: "1979",
    sport: "basketball",
  },
  {
    name: "Vancouver Canucks",
    city: "Vancouver",
    league: "NHL",
    year: "1970",
    sport: "hockey",
  },
  {
    name: "Vancouver Whitecaps FC",
    city: "Vancouver",
    league: "MLS",
    year: "2011",
    sport: "soccer",
  },
  {
    name: "Vegas Golden Knights",
    city: "Paradise",
    league: "NHL",
    year: "2017",
    sport: "hockey",
  },
  {
    name: "Washington Capitals",
    city: "Washington",
    league: "NHL",
    year: "1974",
    sport: "hockey",
  },
  {
    name: "Washington Nationals",
    city: "Washington",
    league: "MLB",
    year: "2005",
    sport: "baseball",
  },
  {
    name: "Washington Redskins",
    city: "Landover",
    league: "NFL",
    year: "1937",
    sport: "football",
  },
  {
    name: "Washington Wizards",
    city: "Washington",
    league: "NBA",
    year: "1973",
    sport: "basketball",
  },
  {
    name: "Winnipeg Blue Bombers",
    city: "Winnipeg",
    league: "CFL",
    year: "1930",
    sport: "football",
  },
  {
    name: "Winnipeg Jets",
    city: "Winnipeg",
    league: "NHL",
    year: "2011",
    sport: "hockey",
  },
];

module.exports = { teams };
